[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

  
[[redirects]]
  from = "/subdirectory/*"
  to = "https://vibrantly-plain-lark.pgsdemo.com//:splat"
  status = 200
  force = true
  headers = {Host = "https://vibrantly-plain-lark.pgsdemo.com/"}
  
[[redirects]]
  from = "/subdirectory"
  to = "https://vibrantly-plain-lark.pgsdemo.com//index.html"
  status = 200
  force = true
  headers = {Host = "https://vibrantly-plain-lark.pgsdemo.com/"}

  [[redirects]]
  from = "/*"
  to = "https://vibrantly-plain-lark.pgsdemo.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://vibrantly-plain-lark.pgsdemo.com/"}

