[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  
[[redirects]]
  from = "/subdirectory/*"
  to = "https://reverseproxy-division--stunned--footbath-sbx-pgsdemo-com.sbx.preview.pagescdn.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://reverseproxy-division--stunned--footbath-sbx-pgsdemo-com.sbx.preview.pagescdn.com"}
